### ISSUE TITLE
Add "search all filters" test

### ISSUE THREAD

**Issue by jpaten** [human-pangenomics/hprc-data-explorer#35]
For each tab, add the following two tests

Test 1 should:
- Select an arbitrary filter
- Read an arbitrary filter option
- Exit the filter menu
- Search for that filter, and select it
- Ensure filter label appears and that filter appears checked in the filter menu
- Repeat for 3-4 filters
Test 2 should:
- Select some filters through the filter menu
- Deselect those filters through the search all filters bar

**Comment by NoopDog** [comment]
Hi @jpaten lets simplify the test as follows:

1. Click into the search all filters box 
2. Verify the box opens
3. Select the first element in box
4. Verify the count in the facet filter matches the count on the table e.g. "Results 1-2 of 2".

Do this for each entity tab. 

Let us know if we need to add any test ids to make this easier. e.g. if you are drilling down to select components etc.

Thanks!

**Comment by jpaten** [comment]
Sounds good @NoopDog ! I'll work on this when I get to it on my board.
