### ISSUE TITLE
Create prototype of assembly entity

### ISSUE THREAD

**Issue by hunterckx** [human-pangenomics/hprc-data-explorer#6]

**Comment by NoopDog** [comment]
[Year1_assemblies_v2_genbank_merged.csv.zip](https://github.com/user-attachments/files/16505339/Year1_assemblies_v2_genbank_merged.csv.zip)

@hunterckx here is an updated file to use as the assembly input. This has the sample data joined.

**Comment by NoopDog** [comment]
Ok @hunterckx here is an update to the update and has a bunch of new columns.
[Year1_assemblies_v2_genbank_final_merged_with_qc.csv](https://github.com/user-attachments/files/16506045/Year1_assemblies_v2_genbank_final_merged_with_qc.csv)

I think we can't make any filters for these at the moment as we don't have a min/max filter implemented so we can just add these columns to the table.

Lets make the annotation columns display by default (these have annotation_file in the column name) and let the QC columns e.g. num_contigs and everything beyond that be optional.

For the Annotation file colun names, for now you can use:

- ASat
- CAT CHM13
- CAT hg38
- DNA BRNN
- Flagger
- HSat
- Repeat Masker
- Seq Dups
- TEF

**Comment by NoopDog** [comment]
Complete
